/**
 * List of component names
 */
export enum ComponentName {
	EbSidebar = "EbSidebar",
	EbIcon = "EbIcon",
	EbHeading = "EbHeading",
	EbButton = "EbButton",
	EbBottombar = "EbBottombar",
	EbCard = "EbCard",
	EbGrid = "EbGrid",
	EbSlider = "EbSlider",
	EbSliderSlide = "EbSliderSlide",
	EbModal = "EbModal",
	EbModalHeader = "EbModalHeader",
	EbModalContent = "EbModalContent",
	EbModalFooter = "EbModalFooter",
	EbDropdown = "EbDropdown",
	EbInput = "EbInput",
	EbLink = "EbLink",
	EbList = "EbList",
	EbListItem = "EbListItem",
	EbTable = "EbTable",
	EbTableRow = "EbTableRow",
	EbTableCell = "EbTableCell",
	EbLabel = "EbLabel",
	EbVStack = "EbVStack",
	EbHStack = "EbHStack",
	EbSearch = "EbSearch",
	EbIconButton = "EbIconButton",
	EbTabs = "EbTabs",
	EbContainer = "EbContainer",
	EbSplitView = "EbSplitView",
	EbSplitViewPane = "EbSplitViewPane",
	EbSheet = "EbSheet",
	EbRadioGroup = "EbRadioGroup",
	EbSelect = "EbSelect"
}