/**
 * List of component names
 */
export enum ComponentName {
	EbSidebar = "EbSidebar",
	EbIcon = "EbIcon",
	EbHeading = "EbHeading",
	EbButton = "EbButton",
	EbBottombar = "EbBottombar",
	EbCard = "EbCard",
	EbGrid = "EbGrid",
	EbSlider = "EbSlider",
	EbSliderSlide = "EbSliderSlide",
	EbModal = "EbModal",
	EbModalHeader = "EbModalHeader",
	EbModalContent = "EbModalContent",
	EbModalFooter = "EbModalFooter",
	EbDropdown = "EbDropdown",
	EbInput = "EbInput",
	EbLink = "EbLink",
	EbTable = "EbTable",
	EbLabel = "EbLabel",
	EbVStack = "EbVStack",
	EbHStack = "EbHStack",
	EbSearch = "EbSearch",
	EbIconButton = "EbIconButton",
	EbTabs = "EbTabs",
	EbSplitView = "EbSplitView",
	EbSplitViewPane = "EbSplitViewPane",
	EbSheet = "EbSheet",
	EbRadioGroup = "EbRadioGroup",
	EbSelect = "EbSelect",
	EbChip = "EbChip",
	EbLoading = "EbLoading",
	EbEmptyState = "EbEmptyState",
	EbRange = "EbRange",
	EbToggle = "EbToggle",
	EbProgress = "EbProgress",
	EbTerminal = "EbTerminal",
	EbTextEditor = "EbTextEditor",
	EbListItem = "EbListItem",
	EbBanner = "EbBanner",
	EbRichText = "EbRichText",
	EbContainer = "EbContainer",
	EbBulletList = "EbBulletList"
}